name: Run ESG Files Daily

on:
  schedule:
    - cron: "0 0 * * *"  # Daily at midnight UTC
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run _ESGManipulation.py
      run: python _ESGManipulation.py

    - name: Run Manipulationnormalfile.py
      run: python Manipulationnormalfile.py

    - name: Commit changes
      run: |
        git config --global user.name "NiamP"
        git config --global user.email "your-email@example.com"
        git add linregressionRevESG.csv
        git add top5prices.csv
        git commit -m "Update CSV file with new data"
        git push origin main
      
